[package]
name = "regen-lang"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^4.2.1"
regex = "^1.7.3"
html-escape = "^0.2.13"

[[bin]]
name = "regen"
path = "src/main.rs"

[lib]
name = "regen"
path = "src/lib.rs"