//! Generated static implementation of the Regen language, generated by Regen itself
//! 
//! This module should only depend on the sdk module.

/* 
 This is the preprocessor file for generated.rs.

 In regen grammar files, you can specify a literal string appended with ";" as a statement to include another file
 The path is relative to the grammar file. This is useful for including import for hook and others

 Included files will always be at the beginning of the generated file.
*/

// Hooks
// Since hooks are defined in the grammar file as literal strings, we need to include the implementation here.
use crate::core::{RuleValue, Param, Hook, LangBuilder};
use crate::core::rule::{parse_rule, parse_rule_value};
use crate::core::param::parse_param;
use crate::core::hook::parse_hook;
use crate::core::token::{parse_token_def, parse_token_ignore_rule, parse_token_rule};
use crate::core::{parse_context, parse_semantic, parse_include};
